Validators final
adrianpalomares/form-app pull request #33
Opened 2021-02-13 07:37 UTC by PaulClefUbeCoding

- Added validators to employee form
- Separated 'information' form group to 2 separate form group that matches the stepper next. First stepper form group is called 'personalInformation' and the next one is 'addressInformation'
- Altered correct changes that used 'information' form group on submitpage html/component and employee html/component to the new form groups
- Currently working on ngIf (has errors so I haven't added it yet, gotta figure it out)

2021-02-13 19:28 UTC, adrianpalomares commented on src/app/form/employee-form/employee-form.component.html
> +          <mat-error>First name is required and must be letters only</mat-error>
Error here. This is for the last name field.

2021-02-13 19:34 UTC, adrianpalomares commented on src/app/form/employee-form/employee-form.component.ts
Can you format this file. Install [Prettier](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode). I also wrote the link to the [shortcuts](https://github.com/PDSeniorDesign/form-app#formatting). It's to prevent merge conflicts in the future.

2021-02-13 19:37 UTC, adrianpalomares commented
Overall, good work! Just fix that typo and format that one file. As far as the ngIf thing. Look into the `form.controls.personalInformation.touched`. There is a property on each form control that tells you whether it has been touched, eg typed on, clicked, etc. Use this because when you move on to the next step the fields are red. It should be after they click on it.

So yeah as soon as you fix those two errors I'll merge

2021-02-13 19:39 UTC, adrianpalomares requested changes
Just format the file and I'll merge. Just saw that you uploaded more commits.

2021-02-14 01:48 UTC, PaulClefUbeCoding commented on src/app/form/employee-form/employee-form.component.ts
Done, reformatted it using prettier

2021-02-14 03:54 UTC, adrianpalomares approved these changes

2021-02-14 03:54 UTC, merged